name: Deploy to Server

on:
  push:
    branches:
      - dev  # Déclenche le workflow sur les push vers la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    

   

    
