name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Mise Ã jour des dispos Jaminco
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SECRET_SERVER }}
        username: ${{ secrets.SECRET_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: ls
